name: SonarQube Analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  sonarQube:
    name: SonarQube Analysis
    runs-on: self-hosted   # Tu runner debe ser Windows

    environment: sonarqube

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"

      - name: Cache SonarScanner packages
        uses: actions/cache@v4
        with:
          path: C:\Users\${{ runner.user }}\.sonar\cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarScanner
        shell: powershell
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner.bat `
            -Dsonar.projectKey=Proyecto-MAThomas `
            -Dsonar.sources=. `
            -Dsonar.host.url="$env:SONAR_HOST_URL" `
            -Dsonar.token="$env:SONAR_TOKEN" `
            -Dsonar.python.version=3.10
